# trigger:
#   branches:
#     include:
#     - main
#     - master

parameters:
  - name: Env
    displayName: Select Region for Deployment
    type: string
    default: "Test"
    values:
      - Test

variables:
  - template: variables.yml

stages:
  - stage: Plan_${{parameters.Env}}
    jobs:
      - deployment:
        environment: "Staging"
        displayName: Plan ${{parameters.Env}}     
        pool:
          vmImage: "$(vmImage)"
        variables:
          - template: ./${{parameters.Env}}/variables.${{parameters.Env}}.yml 
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./template/plan.yml
                  parameters:
                    Env: ${{parameters.Env}}
  
  - stage: Apply_${{parameters.Env}}
    jobs:
      - deployment:
        environment: "Production"
        displayName: Apply ${{parameters.Env}}     
        pool:
          vmImage: "$(vmImage)"
        variables:
          - template: ./${{parameters.Env}}/variables.${{parameters.Env}}.yml 
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./template/apply.yml
                  parameters:
                    Env: ${{parameters.Env}}
  
 
   
